# Generated by Django 4.1.3 on 2022-12-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro'},
        ),
        migrations.AddField(
            model_name='livro',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='pdf',
            field=models.ImageField(blank=True, null=True, upload_to='arquivo_pdf'),
        ),
    ]
